name: Pheasant Web Deploy
on:
  push:
    branches:
      - main
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub global activate pheasant_cli
      # TODO: Work on CLI to Avoid This
      - run: dart pub global activate webdev
      - run: pheasant build --release -o docs
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh-pages --force